### ISSUE TITLE
Multi-event HDF5

### ISSUE THREAD

**Issue by biochem-fan** [antonbarty/cheetah-2017#12]
Dear cheetah developers,

Do you have plans to support outputting multi-event HDF5 files? I don't mean the CXI format, but the one CrystFEL is going to adapt.

Latest developmental version of CrystFEL can handle multiple-event HDF5 files structured as follows:

(1)
event1/detector1/data
event1/detector2/data
...
event1/detector8/data
event2/detector1/data
event2/detector2/data
...
event2/detector8/data
...

(2)
event1/detecor_titled/data
event2/detecor_titled/data
...

My question is, can Cheetah output multi-event files structured this way?

"savehits = 1" produces traditional single-event HDF files through saveFrame.cpp. "saveCXI = 1" produces a multi-event HDF file through saveCXI.cpp. However, CrystFEL cannot handle this CXI format, because multiple-events are stored in a 3D array. We need multi-event files using 2D arrays like (1) or (2).

I made a quick hack in worker.cpp to write a multi-event HDF5 file like (2), but am wondering if there is a plan to officially support this format.

**Comment by FilipeMaia** [comment]
The new CrystFEL version will be able to handle the CXI format.

**Comment by rkirian** [comment]
I thought that the latest crysfel can already handle the cxidb format.  Best to hear from Tom or Valerio on this.

Rick

**Comment by FilipeMaia** [comment]
Yea I'm reasonably sure that the version that can handle the multiple events can also handle cxi files, it's just a question of configuration. It guess an example would be useful here.

**Comment by biochem-fan** [comment]
Thank you very much for quick response.

I didn't know CrystFEL already supports CXI format. Could you please show me
how to specify it in the .geom file?

Currently, I write

 data = /%/detector_tited/data

to read files structured as (2).

**Comment by FilipeMaia** [comment]
I don't have now the document specifying the syntax but it's a small variation of that. Tom or Valerio will be able to easily tell you.

**Comment by rkirian** [comment]
Dear Richard, 
There is no particular format that CrystFEL will adopt. The nice thing about our refactoring of the I/O in CrystFEL is that it should be able to handle any kind of file as long as it is HDF5 and its structure is described in the geometry file. Specifically, CrystFEL can deal with cxidb files, even with 3D data blocks. If needed, I can help with writing the correct description of the format on the geometry file.
One thing needs to be checked: the last time I tried it, Cheetah wrote valid cxidb files, but was actually skipping some events (shots) writing the files, which were then lost. I don't know if this has been fixed... I didn't have time to look at the problem...
Valerio
On Nov 19, 2014 11:51 PM, Richard Kirian richard.kirian@desy.de wrote:I thought that the latest crysfel can already handle the cxidb format.  Best to hear from Tom or Valerio on this.RickOn Nov 19, 2014, at 3:42 PM, biochem_fan notifications@github.com wrote:Dear cheetah developers,Do you have plans to support outputting multi-event HDF5 files? I don't mean the CXI format, but the one CrystFEL is going to adapt.Latest developmental version of CrystFEL can handle multiple-event HDF5 files structured as follows:(1)
event1/detector1/data
event1/detector2/data
...
event1/detector8/data
event2/detector1/data
event2/detector2/data
...
event2/detector8/data
...(2)
event1/detecor_titled/data
event2/detecor_titled/data
...My question is, can Cheetah output multi-event files structured this way?"savehits = 1" produces traditional single-event HDF files through saveFrame.cpp. "saveCXI = 1" produces a multi-event HDF file through saveCXI.cpp. However, CrystFEL cannot handle this CXI format, because multiple-events are stored in a 3D array. We need multi-event files using 2D arrays like (1) or (2).I made a quick hack in worker.cpp to write a multi-event HDF5 file like (2), but am wondering if there is a plan to officially support this format.—Reply to this email directly or view it on GitHub.

**Comment by biochem-fan** [comment]
OK, I got it. 

```
data = /entry_1/data_1/data
dim0 = %
dim1 = ss
dim2 = fs
```

worked for CXIDB format. Thank you very much.

**Comment by valmar** [comment]
Sorry about the lack of documentation. It will be up on the CrystFEL website before the release of the next version. I am glad you could do it anyway. I am available for further questions and bug reports...

**Comment by antonbarty** [comment]
The answer is: yes.

Cheetah can output CXIDB files, and CrystFEL can read them.  
We have been working behind the scenes on this, testing it internally, and most of the development work is done.

We used CrystFEL with CXIDB files on some old data and the results agreed with doing things the old way. We were planning to test it ourselves in a forthcoming experiment (December) to find out annoyances and bugs in the heat of beamtime before making it our normal mode of operation. 

It could be that a development version of CrystFEL is needed, or that a release needs to be made to push the changes into the master version. 

Anton 

---

Anton Barty
Centre for Free Electron Laser Science 
DESY, Notkestrasse 85, 22607 Hamburg, Germany
phone: +49 (0)40 8998 5783
PhD positions available: http://desy.cfel.de/cid/education/doctoralstudies/ http://desy.cfel.de/cid/education/doctoralstudies/

**Comment by biochem-fan** [comment]
Thank you very much for comments.

Yes, I am using the development version of CrystFEL on Git. Moreover, I have modified hdfsee to open .stream files and show a list of crystals in a table. (see https://github.com/biochem-fan/CrystFEL/tree/multievent)

Now I confirmed it on multievent HDF5 files structured in many ways.
1. original (unfiltered, un-corrected) output from SACLA structured as (1)
2. output from my hacked version of Cheetah, structured as (2)
3. CXIDB format from Cheetah

All worked fine. Thanks!

(The reason I did (2) is to keep file size minimum. Although CXIDB stores data in 32bit float, a pixel in our detector is worth only 16 bit integer)

**Comment by FilipeMaia** [comment]
Storing data in CXI files in 32 and 16bit ints wil arrive to the testing branch of cheetah very soon.

**Comment by biochem-fan** [comment]
Wonderful!

**Comment by FilipeMaia** [comment]
I just committed the dataSaveFormat support for CXI files in testing.

**Comment by biochem-fan** [comment]
Thanks. I will try it.
