### ISSUE TITLE
Number of saturated peaks

### ISSUE THREAD

**Issue by biochem-fan** [antonbarty/cheetah-2017#14]
Dear developers,

I have another question. We want to know the number of peaks containing saturated pixel(s) in an image to see if the attenuator thickness is appropriate. Simply counting the number of saturated pixels is not enough because of high background scatterings.

My idea is to
1. remove PIXEL_IS_SATURATED from the definition of mask at https://github.com/antonbarty/cheetah/blob/master/source/libcheetah/src/hitfinders.cpp#L218
2. mark the peak as saturated if a saturated pixel is encountered during loops in peakfinders.cpp 

Is there better way to do this? I would appreciate your suggestion.

**Comment by mhantke** [comment]
Hi!

What about looking for pixels that have both bits options set,
PIXEL_IS_SATURATED and PIXE_IS_IN_PEAKMASK?

Cheers,
Max.

**Comment by antonbarty** [comment]
Hi

Another way to address this is to use the peak lists to plot the maximum intensity in each found peak.
These lists are in text file format so easy to read in anything (even if they are long).

Here is an example, from the cspad in dual-gain mode, where you can clearly see where the peaks are clipping due to saturation.

---

Anton Barty
Centre for Free Electron Laser Science 
DESY, Notkestrasse 85, 22607 Hamburg, Germany
phone: +49 (0)40 8998 5783
PhD positions available: http://desy.cfel.de/cid/education/doctoralstudies/ http://desy.cfel.de/cid/education/doctoralstudies/

**Comment by antonbarty** [comment]
I think the peak mask is used differently to how you expect for crystal data.
It’s the regions of the detector in which to not look for peaks (but allow the data to pass through to the output file without being zeroed out).

A.

---

Anton Barty
Centre for Free Electron Laser Science 
DESY, Notkestrasse 85, 22607 Hamburg, Germany
phone: +49 (0)40 8998 5783
PhD positions available: http://desy.cfel.de/cid/education/doctoralstudies/ http://desy.cfel.de/cid/education/doctoralstudies/

**Comment by antonbarty** [comment]
PS: We haven’t integrated the ‘Run cheetah’ button of the GUI into SACLA processing yet, mainly due to lack of demand.

But it should not be too hard to do so:
That ‘run cheetah’ button calls the ‘process’ script, which in turn calls the ‘hitfinder’ script.  ‘hitfinder’ does some housekeeping (e.g.: creating the output directories) but also finds the XTC files and sends jobs to the SLAC batch farm.  Find those bits in ‘hitfinder’ and change them for the SACLA environment, and the rest of the GUI stuff should just work.  It’s a not-too-intimidating bash script so should be tweak able

Same goes for running anywhere else (ESRF, PetraIII, etc)

Cheers

Anion

---

Anton Barty
Centre for Free Electron Laser Science 
DESY, Notkestrasse 85, 22607 Hamburg, Germany
phone: +49 (0)40 8998 5783
PhD positions available: http://desy.cfel.de/cid/education/doctoralstudies/ http://desy.cfel.de/cid/education/doctoralstudies/

**Comment by biochem-fan** [comment]
Thank you very much for quick response.

> Another way to address this is to use the peak lists to plot the maximum intensity in each found 
> peak. These lists are in text file format so easy to read in anything (even if they are long).

This sounds easier. However, to do this, I have to set pixelSaturationADC higher than the real value because otherwise, saturated pixels are not included in the peak (they are set to 0 in https://github.com/antonbarty/cheetah/blob/master/source/libcheetah/src/peakfinders.cpp#L373), and do not affect maxI.

> PS: We haven’t integrated the ‘Run cheetah’ button of the GUI into SACLA processing yet, mainly due to lack of demand.

In SACLA, a new set of API is being developed so that user programs can directly get images and metadata. I modified your cheetah-sacla to use this API instead of reading HDF5 files. It also pre-filters images based on metadata to further reduce IO. For GUI, I wrote a simple python program to submit jobs and monitor "status.txt" and show progress bars in realtime. I will contribute these once the API is fixed.

**Comment by antonbarty** [comment]
This sounds great - and the contributions to operability at SACLA most welcome!

The GUI has a few other neat features, such as easily viewing images.  But if you don’t need it, a script to do the same is just fine (it is a bit run-based at the moment)

A.

---

Anton Barty
Centre for Free Electron Laser Science 
DESY, Notkestrasse 85, 22607 Hamburg, Germany
phone: +49 (0)40 8998 5783
PhD positions available: http://desy.cfel.de/cid/education/doctoralstudies/ http://desy.cfel.de/cid/education/doctoralstudies/
